In [2]:
import bs4 as BeautifulSoup
import urllib.request
import pandas as pd
import numpy as np
import re
main_url = 'https://www.basketball-reference.com/players/'
#It was not seen prior that there are no players whos surnames start with x, hence an exception was thrown at letter x. 
#To save time, the available array was copied to another array and the remaining letters were processed 
letters = 'abcdefghijklmnopqrstuvwyz'
letters_list = list(letters)

In [3]:
""" htmldata = urllib.request.urlopen('https://www.basketball-reference.com/players/a/')
bsoup = BeautifulSoup.BeautifulSoup(htmldata,'html.parser')
complete_array = None
Data_list = None """
main_array = None
player_id = 640
for letter in letters_list:
    print(letter)
    try:
        htmldata = urllib.request.urlopen('https://www.basketball-reference.com/players/' + letter +'/')
    except:
        continue
    bsoup = BeautifulSoup.BeautifulSoup(htmldata,'html.parser')
    #a placeholder matrix
    complete_array = np.zeros(shape=(1,1))
    Data_list = None
    for i in range(1,len(bsoup.find_all('tr'))):
        #we collect only players who played after 1980
        if int(bsoup.find_all('tr')[i].find('td',{'data-stat':'year_max'}).get_text())>1980:
            href = bsoup.find_all('tr')[i].find_all('a')[0].attrs['href']
            try:
                player_html = urllib.request.urlopen(main_url + letter + "/" + href.split('/')[-1])
            except:
                #due to errors in the html page, some href do not work hence we skip these
                continue
            player_bsoup = BeautifulSoup.BeautifulSoup(player_html,'html.parser')
            #get draft year
            pattern = r'[0-9]\sNBA Draft'
            draft_year_list = player_bsoup.find_all('a',text = re.compile(pattern))
            if (len(draft_year_list)>0):
                draft_year = draft_year_list[0].get_text().split()[0]
            else:
                draft_year = "Undrafted"
            if Data_list == None:
                Data_list = [item.get_text() for item in player_bsoup.find_all('th') if 'aria-label' in item.attrs.keys()]
                Data_list.insert(0,'Name')

            player_dataarray = np.empty(shape = (len(player_bsoup.find_all('tbody')[0].find_all('tr')),len(Data_list)), dtype = np.object)
            for j in range(0,len(player_bsoup.find_all('tbody')[0].find_all('tr'))):
                data_row = [player_bsoup.find_all('h1',{'itemprop':'name'})[0].get_text().strip()]
                #getting season
                try:
                    #some players wont play some years, at those instances, this code will throw exception
                    #hence we continue to the next year
                    data_row.extend([player_bsoup.find_all('tbody')[0].find_all('tr')[j].find_all('th')[0].get_text()])
                    #adding rest of data    
                    [data_row.append(data) for data in [td.get_text() if td.get_text() != "" else np.nan for td in (player_bsoup.find_all                     ('tbody')[0].find_all('tr')[j].find_all('td'))]]    
                except:
                    continue
                try:     
                    player_dataarray[j,:]  = np.array(data_row)
                except:
                    #any player who doesnt have ['Name','Season','Age','Tm','Lg','Pos','G','GS','MP','FG','FGA','FG%','3P','3PA','3P%', '2P''2PA','2P%','eFG%','FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS'] as there stats are not considered. Majority of players after 1980 will have these stats as these were collected and recorded in this era of basketball
                    break
        else:
            continue
        if i == 1:
            player_id = player_id + 1
            id_array = np.array([player_id]*player_dataarray.shape[0]).reshape(-1,1)
            draft_array = np.array([draft_year]*player_dataarray.shape[0]).reshape(-1,1)
            complete_array = np.c_[id_array,player_dataarray,draft_array]
        else:
            player_id = player_id + 1
            id_array = np.array([player_id]*player_dataarray.shape[0]).reshape(-1,1)
            draft_array = np.array([draft_year]*player_dataarray.shape[0]).reshape(-1,1)
            if complete_array.shape != (1,1):
                complete_array = np.vstack((complete_array,np.c_[id_array,player_dataarray,draft_array]))
            else:
                complete_array = np.c_[id_array,player_dataarray,draft_array]
    if letter == letters_list[0]:
        main_array = complete_array
        print(main_array.shape)
    else:
        main_array = np.vstack((main_array,complete_array))
        print(main_array.shape)
        

a
(1036, 33)
b
(3330, 33)
c
(4927, 33)
d
(6140, 33)
e
(6684, 33)
f
(7239, 33)
g
(8467, 33)
h
(10092, 33)
i
(10259, 33)
j
(11565, 33)
k
(12207, 33)
l
(13108, 33)
m
(15370, 33)
n
(15890, 33)
o
(16344, 33)
p
(17443, 33)
q
(17460, 33)
r
(18683, 33)
s
(20412, 33)
t
(21359, 33)
u
(21433, 33)
v
(21738, 33)
w
(23668, 33)
y
(23751, 33)
z
(23802, 33)


In [4]:
temp = np.zeros(shape = (1,1))
temp.shape == (1,1)


True

In [5]:
atoc_array = main_array

In [6]:
atoc_array

array([[641, 'Alaa Abdelnaby', '1990-91', ..., '0.9', '3.1', '1990'],
       [641, 'Alaa Abdelnaby', '1991-92', ..., '1.9', '6.1', '1990'],
       [641, 'Alaa Abdelnaby', '1992-93', ..., '2.5', '7.7', '1990'],
       ...,
       [3856, 'Ivica Zubac', '2018-19', ..., '2.5', '9.4', '2016'],
       [3856, 'Ivica Zubac', '2019-20', ..., '2.3', '8.3', '2016'],
       [3856, 'Ivica Zubac', '2020-21', ..., '2.4', '7.8', '2016']],
      dtype=object)

In [7]:
final_array = np.vstack((atoc_array, main_array))
final_array

array([[641, 'Alaa Abdelnaby', '1990-91', ..., '0.9', '3.1', '1990'],
       [641, 'Alaa Abdelnaby', '1991-92', ..., '1.9', '6.1', '1990'],
       [641, 'Alaa Abdelnaby', '1992-93', ..., '2.5', '7.7', '1990'],
       ...,
       [3856, 'Ivica Zubac', '2018-19', ..., '2.5', '9.4', '2016'],
       [3856, 'Ivica Zubac', '2019-20', ..., '2.3', '8.3', '2016'],
       [3856, 'Ivica Zubac', '2020-21', ..., '2.4', '7.8', '2016']],
      dtype=object)

In [17]:
Data_list

['PlayerID',
 'Name',
 'Season',
 'Age',
 'Tm',
 'Lg',
 'Pos',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 'Draft Year']

In [18]:


final_df = pd.DataFrame(data = main_array, columns = Data_list)
final_df

PlayerID                 Name   Season Age   Tm   Lg Pos   G   GS    MP  \
0          641       Alaa Abdelnaby  1990-91  22  POR  NBA  PF  43    0   6.7   
1          641       Alaa Abdelnaby  1991-92  23  POR  NBA  PF  71    1  13.2   
2          641       Alaa Abdelnaby  1992-93  24  TOT  NBA  PF  75   52  17.5   
3          641       Alaa Abdelnaby  1992-93  24  MIL  NBA  PF  12    0  13.3   
4          641       Alaa Abdelnaby  1992-93  24  BOS  NBA  PF  63   52  18.3   
5          641       Alaa Abdelnaby  1993-94  25  BOS  NBA  PF  13    0  12.2   
6          641       Alaa Abdelnaby  1994-95  26  TOT  NBA  PF  54    0   9.4   
7          641       Alaa Abdelnaby  1994-95  26  SAC  NBA  PF  51    0   9.3   
8          641       Alaa Abdelnaby  1994-95  26  PHI  NBA  PF   3    0  10.0   
9          642  Kareem Abdul-Jabbar  1969-70  22  MIL  NBA   C  82  nan  43.1   
10         642  Kareem Abdul-Jabbar  1970-71  23  MIL  NBA   C  82  nan  40.1   
11         642  Kareem Abdul-Jabbar  1971-72  24  MIL  NBA   C  81  nan  44.2   
12         642  Kareem Abdul-Jabbar  1972-73  25  MIL  NBA   C  76  nan  42.8   
13         642  Kareem Abdul-Jabbar  1973-74  26  MIL  NBA   C  81  nan  43.8   
14         642  Kareem Abdul-Jabbar  1974-75  27  MIL  NBA   C  65  nan  42.3   
15         642  Kareem Abdul-Jabbar  1975-76  28  LAL  NBA   C  82  nan  41.2   
16         642  Kareem Abdul-Jabbar  1976-77  29  LAL  NBA   C  82  nan  36.8   
17         642  Kareem Abdul-Jabbar  1977-78  30  LAL  NBA   C  62  nan  36.5   
18         642  Kareem Abdul-Jabbar  1978-79  31  LAL  NBA   C  80  nan  39.5   
19         642  Kareem Abdul-Jabbar  1979-80  32  LAL  NBA   C  82  nan  38.3   
20         642  Kareem Abdul-Jabbar  1980-81  33  LAL  NBA   C  80  nan  37.2   
21         642  Kareem Abdul-Jabbar  1981-82  34  LAL  NBA   C  76   76  35.2   
22         642  Kareem Abdul-Jabbar  1982-83  35  LAL  NBA   C  79   79  32.3   
23         642  Kareem Abdul-Jabbar  1983-84  36  LAL  NBA   C  80   80  32.8   
24         642  Kareem Abdul-Jabbar  1984-85  37  LAL  NBA   C  79   79  33.3   
25         642  Kareem Abdul-Jabbar  1985-86  38  LAL  NBA   C  79   79  33.3   
26         642  Kareem Abdul-Jabbar  1986-87  39  LAL  NBA   C  78   78  31.3   
27         642  Kareem Abdul-Jabbar  1987-88  40  LAL  NBA   C  80   80  28.9   
28         642  Kareem Abdul-Jabbar  1988-89  41  LAL  NBA   C  74   74  22.9   
29         643   Mahmoud Abdul-Rauf  1990-91  21  DEN  NBA  PG  67   19  22.5   
...        ...                  ...      ...  ..  ...  ...  ..  ..  ...   ...   
23772     3848     Phil Zevenbergen  1987-88  23  SAS  NBA   C   8    0   7.3   
23773     3849          Wang Zhizhi  2000-01  23  DAL  NBA   C   5    0   7.6   
23774     3849          Wang Zhizhi  2001-02  24  DAL  NBA   C  55    0  10.9   
23775     3849          Wang Zhizhi  2002-03  25  LAC  NBA   C  41    1  10.0   
23776     3849          Wang Zhizhi  2003-04  26  TOT  NBA   C  16    0   7.1   
23777     3849          Wang Zhizhi  2003-04  26  LAC  NBA   C   2    0   4.5   
23778     3849          Wang Zhizhi  2003-04  26  MIA  NBA   C  14    0   7.5   
23779     3849          Wang Zhizhi  2004-05  27  MIA  NBA   C  20    0   4.6   
23780     3850         George Zídek  1995-96  22  CHH  NBA   C  71   21  12.5   
23781     3850         George Zídek  1996-97  23  TOT  NBA   C  52    2   7.2   
23782     3850         George Zídek  1996-97  23  CHH  NBA   C  36    2   8.0   
23783     3850         George Zídek  1996-97  23  DEN  NBA   C  16    0   5.5   
23784     3850         George Zídek  1997-98  24  TOT  NBA   C  12    0   5.3   
23785     3850         George Zídek  1997-98  24  DEN  NBA   C   6    0   7.0   
23786     3850         George Zídek  1997-98  24  SEA  NBA   C   6    0   3.7   
23787     3851    Derrick Zimmerman  2005-06  24  NJN  NBA  PG   2    0  16.0   
23788     3852    Stephen Zimmerman  2016-17  20  ORL  NBA   C  19    0   5.7   
23789     3853          Paul Zipser  

In [19]:
final_df.to_csv('NBAData.csv',index = False)

In [13]:
main_array

array([[641, 'Alaa Abdelnaby', '1990-91', ..., '0.9', '3.1', '1990'],
       [641, 'Alaa Abdelnaby', '1991-92', ..., '1.9', '6.1', '1990'],
       [641, 'Alaa Abdelnaby', '1992-93', ..., '2.5', '7.7', '1990'],
       ...,
       [3856, 'Ivica Zubac', '2018-19', ..., '2.5', '9.4', '2016'],
       [3856, 'Ivica Zubac', '2019-20', ..., '2.3', '8.3', '2016'],
       [3856, 'Ivica Zubac', '2020-21', ..., '2.4', '7.8', '2016']],
      dtype=object)

['PlayerID',
 'Name',
 'Season',
 'Age',
 'Tm',
 'Lg',
 'Pos',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 'Draft Year']